apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: ng-angular-image:latest1
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort
